apiVersion: v1
kind: Service
metadata:
  name: {{ include "shippingservice.name" . }}
  labels:
    {{- include "shippingservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50051
      name: grpc
  selector:
    {{- include "shippingservice.selectorLabels" . | nindent 4 }}
