apiVersion: v1
kind: Service
metadata:
  name: {{ include "productcatalogservice.name" . }}
  labels:
    {{- include "productcatalogservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3550
      name: grpc
  selector:
    {{- include "productcatalogservice.selectorLabels" . | nindent 4 }}
