apiVersion: v1
kind: Service
metadata:
  name: {{ include "paymentservice.name" . }}
  labels:
    {{- include "paymentservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50051
      name: grpc
  selector:
    {{- include "paymentservice.selectorLabels" . | nindent 4 }}
